{
    'name': 'Hotel Management',
    'version': '1.0',
    'summary': 'Comprehensive hotel management system integrating booking, POS, and reporting',
    'description': 'Module for managing hotel operations including room booking, restaurant/bar POS, and more.',
    'author': 'Raizada Resorts',
    'website': 'https://www.yourcompany.com',
    'category': 'Hospitality',
    'depends': [
    'base',
    'sale',
    
    'mail',
    'point_of_sale',
    'stock',
    'calendar',
    'website',
    'uom',
],
    'data': [
        'security/hotel_security.xml',
        'security/ir.model.access.csv',
        'views/room_views.xml',
        'views/room_type_views.xml',
        'views/room_amenity_views.xml',
        'views/room_maintenance_views.xml',
        'views/room_pricing_views.xml',
        'views/booking_views.xml',
        'views/guest_views.xml',
        'views/pos_views.xml',
        'views/membership_views.xml',
        'views/accounting_views.xml',
        'data/mail_template_data.xml',
        'data/hotel_sequence.xml',
    ],
    'demo': ['demo/hotel_demo.xml'],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}